language: php
before_script:
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher
  - phpenv config-add travis.php.ini
  - mailcatcher
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
before_install:
  - composer install --ignore-platform-reqs
script:
  - php vendor/bin/phpunit ./tests/
